name: Release APWorld
on:
  workflow_dispatch: # Enables the manual trigger button
  push:
    tags:
      - '**'
jobs:
  release:
    uses: gerbiljames/ap-actions/.github/workflows/release-apworld.yml@standard-build-apworld
    with:
      apworld-path: worlds/TowerOfBabel
      ap-version: '0.6.7'
      python-version: '3.13'
      prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc')}}
